### PR TITLE
Fix/https backend

### LINKED ISSUE #150: CHANGE BEFORE PRODUCTION: For the backend, HTTPS must be used everywhere.
On our project, it is possible to bypass https and that is a problem. I'll investigate into that

Subject:

Image

Eval sheet:

Image

### PR DESCRIPTION
**Pull request by schardot**
# PR #231 – End‑to‑End HTTPS (Quick & Understandable)

## What this PR does (TL;DR)

This PR enforces **HTTPS everywhere** across the whole stack. There is **no HTTP fallback**.
If SSL certificates are missing, services **fail fast at startup**.

**Result:** all traffic is encrypted — frontend ↔ nginx ↔ gateway ↔ services ↔ services.

---

## Why this exists

* **Evaluation requirement:** *"All communication between frontend and backend must be encrypted using HTTPS"*
* **Security best practice:** internal Docker traffic is **not trusted**
* **Fail‑fast by design:** better to crash than run insecurely

HTTPS only at nginx is **not enough** — nginx → services and service → service traffic would still be plaintext.

---

### 1. HTTPS is mandatory everywhere

* Frontend (nginx)
* API Gateway
* All backend services (user, game, chat, presence, notification)
* All service‑to‑service calls

➡️ Services **exit on startup** if certificates are missing.

---

### 2. Self‑signed certificates (dev)

A new script generates certs for **every service**:

```
./scripts/generate-ssl-certs.sh
```

* RSA 2048
* Valid for 365 days
* One cert/key per service

> Certificates are **ignored by git** (dev only). Production must use real CA certs.

---

### 3. API Gateway

* Always starts in **HTTPS mode** (Fastify `https` option)
* All upstreams are **hardcoded to https://**
* No protocol detection, no fallback

Example:

```
/api/users → https://user:3003
/api/game  → https://game:3002
```

---

### 4. Backend services

* Fastify configured with HTTPS **in the constructor** (Fastify v5 requirement)
* Startup checks ensure cert + key exist
* HTTP support completely removed

If certs are missing:

```
ERROR: SSL certificates are required but not found
```

---

### 5. Nginx (reverse proxy)

**Production:**

* Client → nginx → gateway → services = HTTPS
* `proxy_ssl_verify off` (self‑signed dev certs)

**Dev:**

* Frontend dev server stays HTTP (Vite limitation)
* API calls still go through **HTTPS gateway**

---

### 6. Docker changes

* SSL certs mounted into each container (read‑only)
* Healthchecks switched to HTTPS with `curl -k`
* `SSL_ENABLED` removed
* `NODE_TLS_REJECT_UNAUTHORIZED=0` for self‑signed dev certs

---

### 1. Generate certificates

```
./scripts/generate-ssl-certs.sh
```

### 2. Start stack

```
docker compose up --build
```

### 3. Verify

```
curl -k https://localhost:3000/health   # API Gateway
curl -k https://localhost:8443           # Frontend via nginx
```

WebSockets must use `wss://`.

---

## Breaking changes

* ❌ `http://` endpoints no longer work
* ❌ Services won’t start without certs
* ✅ All APIs now require `https://`
* ✅ WebSockets use `wss://`

---

## Production notes

Before production:

* Replace self‑signed certs with CA‑signed ones (Let’s Encrypt, etc.)
* Set `NODE_TLS_REJECT_UNAUTHORIZED=1`
* Enable `proxy_ssl_verify on`
* Store certs via proper secret management

---

## Bottom line

* Meets **evaluation requirements**
* Enforces **security by design**
* Prevents accidental insecure deployments
* Clear failure mode, easy to debug

HTTPS is no longer optional — and that’s intentional.

### CODE REVIEW

File: frontend/Dockerfile
Comment (schardot) [inline frontend/Dockerfile:1]: Unlike other services, frontend needs the certificates at build time. So the dockerflle had to handle copying the certificates inside (which should be created manually running the script)

> The frontend container:
> 
> - Terminates TLS itself
> 
> - Needs cert paths hardcoded in nginx.conf
> 
> - Runs as non-root (nginx)
> 
> - Reads certs from /etc/nginx/ssl
> 
> So nginx requires:
> 
> - The directory to exist
> 
> - Correct ownership & permissions
> 
> - Certs to be readable by the nginx user
> 
> That means the image must prepare the filesystem.

File: init-scripts/test-scripts/user-service/login.sh
Comment (schardot) [inline init-scripts/test-scripts/user-service/login.sh:1]: the -k flag in curl tells curl to trust the certificates (since they are self signed)

File: nginx/nginx.conf
Comment (schardot) [inline nginx/nginx.conf:1]: proxy_ssl_verify off is necessary since we are using self signed certificates, otherwise nginx would fail over this. 
also upstream tries to add http by default

File: services/chat-service/src/server.ts
Comment (schardot) [inline services/chat-service/src/server.ts:1]: Read the certificates that were imported and fails quickly if they are not present.

File: services/game-service/src/app.js
Comment (schardot) [inline services/game-service/src/app.js:1]: Reads the certificates and fails quickly if they were not imported

File: docker-compose.dev.yml
Comment (schardot) [inline docker-compose.dev.yml:1]: volumes are created so the certs arent baked into images (safer)

healthchecks are updated to use -k to trust self signed certificates

File: docker-compose.dev.yml [hunk 1]
```diff
@@ -172,6 +178,9 @@ services:
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       JWT_SECRET: ${JWT_SECRET}
+      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-0}
```
Comment (schardot) [inline docker-compose.dev.yml:184]: This is telling node not to reject TLS if the certificates cannot be verified. Only services that make http requests to other services (in our case, gateway and user) need this. Other services just receive requests so ok

File: .github/workflows/ci.yml
Comment (schardot) [inline .github/workflows/ci.yml:1]: Added cert generation in our ci.yml otherwise tests would just straight up fail
